### PR TITLE
tests: add fixedTemplates

### PR DESCRIPTION
**Pull request by jamescdavis**
Add a `fixedTemplate` for each test case to test fixing.

### CODE REVIEW

**Comment by jamescdavis** [comment]
I guess this won't run CI because https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/blob/98350ec4bd860a91e5e513c3e718f60d2f997116/.travis.yml#L6-L8 but `yarn lint:js` and `yarn test` pass locally.
(with both locked deps and `yarn install --no-lockfile`)

**Comment by dcyriller** [comment]
Thank you @jamescdavis for both the test and telling us about the CI. I've switched to using GH actions: CI should work if you rebase your PR.

**Comment by dcyriller** [comment]
Thank you @jamescdavis!

**Comment by dcyriller** [comment]
This is really helping :)

**Pull request merged**
